### ISSUE TITLE
the plugin is affecting my css

### ISSUE THREAD

**Issue by stevesmith1** [aaronhuisinga/wordpress-employment#2]
Hi great plugin, when i place the shortcodes in the respective pages it haves my text that describes the content to the bottom, would you know why?

**Comment by aaronhuisinga** [comment]
It probably has something to do with the plugin requiring bootstrap. I really need to budget some time in the next month or so to re-write a large portion of the plugin. I've actually performed some updates to it outside of Github (added some new features), but they're pretty hacky and I haven't had the time to clean them up. Give me a few weeks here to get more work done on this.

**Comment by jimbaldwin1137** [comment]
Thank you for your response. In the meantme we had to re-install WordPress and un-install the plugin. We would like to have it working though as we saw some great improvement in speed while it was working. Please email me when you resolve the issue.
 
Jim Baldwin
Manager Of Marketing Technology, Webmaster
DISCOVER PALM BEACH COUNTY
http://www.palmbeachfl.com/

561-839-0283
321-574-5740

**Comment by aaronhuisinga** [comment]
The old version of the plugin was most certainly conflicting with JS and CSS on several blogs. This has been fixed in 0.5.0 as files are now properly namespaced and registered via WordPress functions.

Sorry it took so long to get these issues resolved. Real life got in the way for a long while (started a new company), but I'm finally about caught up on modernizing the plugin. New version should be merged this week.
